import portifolio from "@/assets/images/web_siite_portifolio.png";
import previsao from "@/assets/images/previsao.png";
import vestuario from "@/assets/images/vestuario.png";

export const projects = [
  {
    id: 0,
    title: "Web-site-Portifólio",
    status: "Concluído",
    description:
      "Uma aplicação web com o formato SPA - Single Page Application, com o intuito de ser moderna, agradável aos olhos, de fácil navegação, responsiva e que mostra um pouco dos recursos iniciais que o React tem a oferecer.",
    image: portifolio,
    tags: [
      "React;  ",
      "Styled Components;  ",
      "Typewriter - Effect;  ",
      "Emailjs;  ",
      "Material-Icons;  ",
      "React-Router-Dom;  ",
    ],
    github: "https://github.com/leofrs/vestuario-React",
    webapp: "https://portifolio-website-three.vercel.app",
  },
  {
    id: 1,
    title: "The Prevision",
    status: "Concluído",
    description:
      "Essa aplicação foi desenvolvida para a compreensão prática de como utilizar o axios na requisição de API's, custom hooks para a separação do que é código javascript e do que é jsx,hook useRef para evitar a re-render do componente ao digitar no campo do input",
    image: previsao,
    tags: [
      "React Js;  ",
      "TailwindCSS;  ",
      "React icons;  ",
      "Axios;  ",
      "Custom Hooks;  ",
      "API;  ",
    ],
    github: "https://github.com/leofrs/previsao-do-tempo",
    webapp: "https://previsao-do-tempo-teal-nine.vercel.app/",
  },
  {
    id: 2,
    title: "The Clothing",
    status: "Em andamento...",
    description:
      "Essa aplicação está sendo desenvolvida para abranger vários aspectos do desenvolvimento front-end, sendo eles: Login, autenticação e cadastro de usúario, implementação com um banco de dados(que nesse caso é o do firebase), custom hooks, requisição de API, Axios, Rotas, Sass para estilização, Redux toolkit para gerenciamento de estado e react icons para icones. ",
    image: vestuario,
    tags: [
      "React Js;  ",
      "Firebase;  ",
      "Axios;  ",
      "Requisição de API;  ",
      "Reduz Toolkit;  ",
      "Custom Hooks;  ",
      "React-icons;  ",
      "React-Router-Dom;  ",
      "Sass;  ",
    ],
    github: "https://github.com/leofrs/website-vestuario",
    webapp: "https://website-vestuario.vercel.app/",
  },
];

export const Full_stack = [
  {
    id: 1,
    skill_name: "Html 5",
    Image: "/html.png",
    width: 80,
    height: 80,
  },
  {
    id: 2,
    skill_name: "Css",
    Image: "/css.png",
    width: 80,
    height: 80,
  },
  {
    id: 3,
    skill_name: "Java Script",
    Image: "/js.png",
    width: 65,
    height: 65,
  },
  {
    id: 4,
    skill_name: "Tailwind Css",
    Image: "/tailwind.png",
    width: 80,
    height: 80,
  },
  {
    id: 5,
    skill_name: "Material UI",
    Image: "/mui.png",
    width: 80,
    height: 80,
  },
  {
    id: 6,
    skill_name: "React",
    Image: "/react.png",
    width: 80,
    height: 80,
  },
  {
    id: 7,
    skill_name: "Redux",
    Image: "/redux.png",
    width: 80,
    height: 80,
  },
  {
    id: 8,
    skill_name: "React Query",
    Image: "/reactquery.png",
    width: 80,
    height: 80,
  },
  {
    id: 9,
    skill_name: "Type Script",
    Image: "/ts.png",
    width: 80,
    height: 80,
  },
  {
    id: 10,
    skill_name: "Next js 13",
    Image: "/next.png",
    width: 80,
    height: 80,
  },
  {
    id: 11,
    skill_name: "Framer Motion",
    Image: "/framer.png",
    width: 80,
    height: 80,
  },
  {
    id: 12,
    skill_name: "Node js",
    Image: "/node-js.png",
    width: 80,
    height: 80,
  },
  {
    id: 13,
    skill_name: "Mongo db",
    Image: "/mongodb.png",
    width: 40,
    height: 40,
  },
  {
    id: 14,
    skill_name: "My SQL",
    Image: "/mysql.png",
    width: 70,
    height: 70,
  },
  {
    id: 15,
    skill_name: "Express js",
    Image: "/express.png",
    width: 80,
    height: 80,
  },
];
